include: package:flutter_lints/flutter.yaml

analyzer:
    plugins:
        - custom_lint
    exclude:
        - lib/**.g.dart
        - lib/**.freezed.dart
linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    use_build_context_synchronously: false
formatter:
  page_width: 120
  trailing_commas: preserve
