name: der_die_das
description: A fun German articles quiz game
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons:
  intl:
  collection:
  gap:
  settings_ui:
  auto_size_text:
  drift:
  sqlite3_flutter_libs:
  path_provider:
  path:
  archive:
  flutter_riverpod:
  freezed_annotation:
  theme_tailor_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  arb_generator:
  drift_dev:
  build_runner:
  freezed:
  theme_tailor:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/db/db.zip
  fonts:
    - family: Lovelo
      fonts:
        - asset: assets/fonts/Lovelo-Black.otf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: "l10n_"
  csv_settings:
    delimiter: ";"
    description_index: 1
    base_index: 2
