name: der_die_das
description: A fun German articles quiz game
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons:
  intl:
  collection:
  gap:
  settings_ui:
  auto_size_text:
  drift:
  sqlite3_flutter_libs:
  path_provider:
  path:
  archive:
  flutter_riverpod:
  freezed_annotation:
  riverpod_annotation:
  theme_tailor_annotation:
  url_launcher:
  flutter_svg:
  go_router:
  flutter_animate:
  flutter_tts:
  audioplayers:
  hive_ce:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  arb_generator:
  drift_dev:
  build_runner:
  freezed:
  theme_tailor:
  riverpod_generator:
  custom_lint:
  riverpod_lint:
  golden_toolkit:
  flutter_launcher_icons:
  icon_font_generator:
  mocktail:
  app_store_screenshots:
    git:
      url: https://github.com/defuncart/app_store_screenshots
      ref: main

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/db/db.zip
    - assets/images/settings/
    - assets/sfx/
  fonts:
    - family: Lovelo
      fonts:
        - asset: assets/fonts/Lovelo-Black.otf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/custom_icons.ttf

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: "l10n_"
  csv_settings:
    delimiter: ";"
    base_index: 1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets_dev/app_icons/app_icon.png"
  adaptive_icon_background: "#ECF0F1"
  adaptive_icon_foreground: "assets_dev/app_icons/android_icon_foreground.png"
  adaptive_icon_monochrome: "assets_dev/app_icons/android_icon_foreground.png"
  macos:
    generate: true
    image_path: "assets_dev/app_icons/app_icon_macos.png"
